apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-home
  description: Joe's Backstage application.
  annotations:
    github.com/project-slug: joebelford/backstage-home
    # backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: guests
  lifecycle: experimental
