---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: unifi
  annotations:
    'backstage.io/kubernetes-id': unifi
    'backstage.io/kubernetes-namespace': unifi
    # backstage.io/kubernetes-label-selector: '<label-selector>'
spec:
  type: service
  lifecycle: experimental
  owner: guests
